### ISSUE TITLE
Minify ONLY the inline css

### ISSUE THREAD

**Issue by peterbe** [shkuznetsov/gulp-minify-inline#11]
Great gulp package! But I only want to minify the `<style>` tags. Not the `<script>` tags. I can accomplish this by doing:
```javascript
  .pipe(minifyInline({
    jsSelector: 'pleasedontminifyscripts'
  }))
```

**Comment by shkuznetsov** [comment]
Yep:
```javascript
  .pipe(minifyInline({
    css: false
  }))
```

**Comment by peterbe** [comment]
Any chance of a new release with this new feature in it?

**Comment by shkuznetsov** [comment]
Sorry, didn't make this clear: it has been there since very beginning, it is also mentioned in the spec:

* `js` contains parameters to pass to UglifyJS2 (for documetation refer to the project homepage). **Set it to false to disable JS uglification globally**.

There is also a test in the suite, which covers that case, so I'm fairly certain it works.

**Comment by peterbe** [comment]
Oops. Then I totally missed that. Thanks for your help.
