### ISSUE TITLE
takes for ever to complete minification

### ISSUE THREAD

**Issue by jpatel3** [shkuznetsov/gulp-minify-inline#17]
I think there is some import conflict or reference error, it takes forever to complete. Is there any verbose mode when the task is in progress. It will help to get the actual error.

**Comment by shkuznetsov** [comment]
No, unfortunately your options are limited to the respective options of the underlying minification plugins, which AFAIK don't support verbose debug. Could you please provide more information (attach a test case) so that I could have a look at your issue? Without that it is really hard to guess what's going on there.

**Comment by jpatel3** [comment]
I figured the issue later, it was because of some es6 syntax in a portion of my js code. It took some trial and error, removing a number of js it was applying minification to. Closing it for now.
