### ISSUE TITLE
Problem with non-english characters

### ISSUE THREAD

**Issue by dimoooooooon** [shkuznetsov/gulp-minify-inline#3]
It changes all non-english characters(ñçáà, джйё,...) to &xxx; format. Don't you know how to turn it off?

**Comment by shkuznetsov** [comment]
Hello, sorry for not answering straight away. Where exactly that happens? I would expect that happens because basically the plugin uses cheerio, which tokenizes the whole HTML and doesn't work around non-ASCII characters nicely. I'll have a look into it and it would be helpful if you gave me a bit more details. Thanks, Alexander.

**Comment by shkuznetsov** [comment]
Added a test, published new release to npm.
